### PR TITLE
Db migrate

### PR DESCRIPTION
**Pull request by andreGarvin**
Check it out @ozzie1998, can we skype call

### CODE REVIEW

**Comment by ozzie1998** [comment]
Discord? I do have Skype, and my logins. Somewhere.

**Comment by andreGarvin** [comment]
I do not have a discord
I followed you on twitter,
Il just message you there

**Comment by EvanCarroll** [comment]
@andreGarvin here, use this gravatar and resubmit.

**Comment by ozzie1998** [comment]
EvanCarrol, you aren't welcome. Get out.

**Comment by EvanCarroll** [comment]
Just saying #5 was closed before it got a satisfactory answer and perhaps it should be addressed.

**Comment by ozzie1998** [comment]
because it wasn't an issue. It was you trolling.

**Comment by ozzie1998** [comment]
Okay, we are no longer using  generatePassword.js. That is going to be replaced with a default password and username for testing Yarn/NPM compatibility with Rocket. What is the CLI for, I am confused? Are you suggesting that we compete with Facebook?

**Comment by ozzie1998** [comment]
Okay, going to accept this PR, but will be adding the generatePassword.js to the .gitignore as we don't need it.

**Pull request merged**
